<template>
  <div class="loadingio-spinner-rolling-k1pkx4bjho">
    <div class="ldio-vw4l91frii8">
      <div></div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-vw4l91frii8 {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-vw4l91frii8 div {
  position: absolute;
  width: 39px;
  height: 39px;
  border: 5px solid #ffffff;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-vw4l91frii8 div {
  animation: ldio-vw4l91frii8 1s linear infinite;
  top: 50px;
  left: 50px;
}
.loadingio-spinner-rolling-k1pkx4bjho {
  width: 54px;
  height: 54px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-vw4l91frii8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.54);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-vw4l91frii8 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
